name: Docker Build 
on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # ✅ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # ✅ Build Docker image
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: sneh1919/sql-injection-detector:latest 


      - name: Run Container Locally for Testing
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull sneh1919/sql-injection-detector:latest
          docker run -d -p 8080:8080 --name sql-test sneh1919/sql-injection-detector:latest
          sleep 10  # Wait for server to start
          curl -f http://localhost:8080/docs || (echo "Service did not start" && exit 1)

           
          
