name: Deploy to Google Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/auth@v2
      with:
        version: 'latest'
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
      
    - name: Log in to DockerHub
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "sneh1919" --password-stdin

    - name: Pull Docker Image from DockerHub
      run: |
        docker pull your-dockerhub-username/sqlinjection-detector:latest

    - name: Retag Docker Image for GCR
      run: |
        docker tag sneh1919/sqlinjection-detector:latest gcr.io/refined-cortex-454302-p3/sqlinjection-detector:latest

    - name: Push Docker Image to GCR
      run: |
        docker push gcr.io/refined-cortex-454302-p3/sqlinjection-detector:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy sqlinjection-detector \
          --image gcr.io/refined-cortex-454302-p3/sqlinjection-detector:latest \
          --platform managed \
          --region asia-southeast1 \
          --allow-unauthenticated
