name: Deploy Docker Image to Google Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Verify gcloud installation
      run: gcloud info

    - name: Log in to DockerHub
      run: |
        echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "sneh1919" --password-stdin

    - name: Pull Docker Image from DockerHub
      run: |
        docker pull sneh1919/sqlinjection-detector:latest

    - name: Retag Docker Image for GCR
      run: |
        docker tag sneh1919/sqlinjection-detector:latest asia-southeast1-docker.pkg.dev/refined-cortex-454302-p3/sqlinjection-detector:latest

    - name: Authenticate Docker with Google Cloud Registry
      run: |
        gcloud services enable artifactregistry.googleapis.com
        gcloud auth configure-docker asia-southeast1-docker.pkg.dev

    - name: Create Artifact Registry if it doesn’t exist
      run: |
        REPO_EXISTS=$(gcloud artifacts repositories list --filter="name:sqlinjection-detector" --format="value(name)")
        if [[ -z "$REPO_EXISTS" ]]; then
          echo "Creating Artifact Registry..."
          gcloud artifacts repositories create sqlinjection-detector \
            --repository-format=Docker \
            --location=asia-southeast1 \
            --description="Docker repository for SQL Injection Detector"
        else
          echo "Artifact Registry already exists."
        fi

    - name: Push Docker Image to GCR
      run: |
        docker push asia-southeast1-docker.pkg.dev/refined-cortex-454302-p3/sqlinjection-detector:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy sqlinjection-detector \
          --image asia-southeast1-docker.pkg.dev/refined-cortex-454302-p3/sqlinjection-detector:latest \
          --platform managed \
          --region asia-southeast1 \
          --allow-unauthenticated
