name: Deploy to Google Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | gcloud auth activate-service-account --key-file=-
        gcloud auth configure-docker gcr.io

    - name: Log in to DockerHub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Pull Docker Image from DockerHub
      run: |
        docker pull your-dockerhub-username/sqlinjection-detector:latest

    - name: Retag Docker Image for GCR
      run: |
        docker tag your-dockerhub-username/sqlinjection-detector:latest gcr.io/${{ secrets.GCP_PROJECT_ID }}/sqlinjection-detector:latest

    - name: Push Docker Image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sqlinjection-detector:latest

    - name: Deploy to Google Cloud Run
      run: |
        gcloud run deploy sqlinjection-detector \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/sqlinjection-detector:latest \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
