name: Deploy to Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      SERVICE_NAME: sql-injection-detector
      REGION: asia-south1
      DOCKER_HUB_IMAGE: snehapriya/sql-injection-detector:latest

    steps:
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Pull from Docker Hub
        run: |
          echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
          docker pull sneh1919/sql-injection-detector:latest 

      - name: Tag and Push to Artifact Registry
        run: |
          docker tag $DOCKER_HUB_IMAGE ${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/sql-injection-detector:$GITHUB_SHA
          docker push ${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/sql-injection-detector:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.REGION }}-docker.pkg.dev/$PROJECT_ID/sql-injection-detector:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated

      - name: Test Cloud Run Endpoint
        run: |
          ENDPOINT=$(gcloud run services describe $SERVICE_NAME --region $REGION --format 'value(status.url)')
          curl -X POST "$ENDPOINT/predict/" -F "file=@test_data.csv"
