  run-and-test:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    
      # ✅ Pull the Docker image
      - name: Pull Docker image
        run: |
          docker pull sneh1919/sql-injection-detector:latest

      # ✅ Run Docker container
      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 snehapriya/sql-injection-detector:latest
          sleep 5

      # ✅ Upload test file and check for SQL Injection
      - name: Test SQL Injection Detection
        run: |
          echo "SELECT * FROM users WHERE id=1 OR 1=1;" >> test_data.csv
          curl -X POST "http://localhost:8000/predict/" -F "file=@test_data.csv"

      # ✅ Stop container after test
      - name: Stop Docker container
        if: always()
        run: |
          docker ps -q --filter "ancestor=snehapriya/sql-injection-detector:latest" | xargs -r docker stop
